name: time_series_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - polars
  - pyarrow
  - scikit-learn
  - matplotlib
  - seaborn
  - requests
  - pydantic
  - ruff
  - pre-commit
  - pip
  - pip:
      - yfinance
